### ISSUE TITLE
Editing an existing main issue on Microsoft Edge

### ISSUE THREAD

**Issue by ajtruckle** [ejyothi/MantisBT-MarkDownEditor#2] opened 2017-02-27 20:13 UTC
As you know, at the moment the toolbar does not display on Microsoft Edge. And if I go to edit the main topic on Microsoft Edge nothing displays in the text boxes.

I can edit the topics with Firefox etc. though.

**Comment by libregeek** [comment] 2017-03-14 09:17
@ajtruckle I haven't changed anything with respect to browser compatibility. Can you please check upstream repository (https://github.com/NextStepWebs/simplemde-markdown-editor) for any possible browser compatibility issues?

**Comment by ajtruckle** [comment] 2017-03-14 09:24
Hi

Already asked and got nowhere. I had to remove your plugin as people couldn't use mantis. 🤔

Andy

Sent from my iPhone

On 14 Mar 2017, at 09:17, Manilal <notifications@github.com<mailto:notifications@github.com>> wrote:


@ajtruckle<https://github.com/ajtruckle> I haven't changed anything with respect to browser compatibility. Can you please check upstream repository (https://github.com/NextStepWebs/simplemde-markdown-editor) for any possible browser compatibility issues?

**Comment by libregeek** [comment] 2017-03-14 09:29
I guess you should report this issue in upstream repository. I don't use Edge, so I may not be able to reproduce the issue.

**Comment by ajtruckle** [comment] 2017-03-14 09:37
Well, it is not a case of if you use edge. If you expose a plugin for the community you really have to test it on multiple platforms. Certainly the core ones. Otherwise it is an unstable plugin and people won't use it. We aren't java developers. 😀

Sent from my iPhone

On 14 Mar 2017, at 09:29, Manilal <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess you should report this issue in upstream repository. I don't use Edge, so I may not be able to reproduce the issue.

**Comment by libregeek** [comment] 2017-03-14 09:53
I found a similar issue in Google Chrome and fixed it just now. I think it should fix the Edge issue also. Can you please test it?

**Comment by ajtruckle** [comment] 2017-03-14 10:02
I will check, but, do we have a resolution for the “note” because we really need that to work too as it is used the most.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by libregeek** [comment] 2017-03-14 10:46
Couple of clarifications:
**Regarding use of MS Edge**: I believe this is how FOSS or community projects are being developed and maintained. If everyone is *just* the user, then there won't be any FOSS projects in this world. I'm not making any money from these and I can't invest more on testing on platforms which doesn't makes sense to me. I released the source code to community since it *worked for me*. As the license for this plugin states, I can't guarantee.. You are free to fork, modify and redistribute it. :)

**Note Issue**: I have submitted a PR for adding an ID to the Note field. I don't know whether it will be accepted by MantisBT maintainers or when it will be merged.

**Comment by ajtruckle** [comment] 2017-03-14 11:22
Fair points ... [😊]


________________________________

**Comment by ajtruckle** [comment] 2017-03-14 12:47
It seems to work well. Now the additional notes edit box is not disabled on edge and also all the bars show up.

**Comment by ajtruckle** [comment] 2017-03-14 17:25
Looks it has been merged. Does this mean I can download a new MantisBT to test?

**Comment by atrol** [comment] 2017-03-14 18:08
> Does this mean I can download a new MantisBT to test?

The change will be included in version 2.3.0, see `Fixed in Version` of the [issue](https://www.mantisbt.org/bugs/view.php?id=22423).

You could use a [Nightly Build](https://www.mantisbt.org/builds.php), which should be available tomorrow, if you don't want to wait for 2.3.0 (should be available end of March). Use the nightly build at your own risk.

**Comment by libregeek** [comment] 2017-03-29 09:38
The original bug in this issue report seems to be fixed. We will have to wait for Mantis-2.3 to enable SimpleMDE for Note textarea.

**Closed as completed by libregeek** 2017-03-29 09:38 UTC
Labels: bug
